### ISSUE TITLE
add CI for circuit + lib + spartan tests

### ISSUE THREAD

**Issue by lsankar4033** [personaelabs/spartan-ecdsa#21]
note https://github.com/personaelabs/spartan-ecdsa/pull/20#issuecomment-1410832123

**Comment by DanTehrani** [comment]
GitHub action setup under my GitHub account: https://github.com/DanTehrani/spartan-ecdsa
(didn't want to debug GitHub actions in this repo)

**Comment by DanTehrani** [comment]
Done!
