### ISSUE TITLE
Implement the verifier in Halo2 

### ISSUE THREAD

**Issue by DanTehrani** [personaelabs/spartan-ecdsa#25]
_**Deprecated**_

- [ ] Re-implement Spartan in Rust. This will be the spec of the verifier circuit.
   - [Hoplite](https://github.com/personaelabs/Hoplite)
- [ ] Implement the circuit using [PSE's fork of Halo2](https://github.com/privacy-scaling-explorations/halo2).
- [ ] Compile the verifier circuit into EVM code using [snark-verifier](https://github.com/privacy-scaling-explorations/snark-verifier).

**Comment by tronch0** [comment]
Hi @DanTehrani, if I can help and participate in the effort (it's Ron from discord) - will be happy to!

**Comment by DanTehrani** [comment]
@tronch0  Hi Ron, that would be amazing!
I’ll get back to u soon with some todos

**Comment by DanTehrani** [comment]
@tronch0 
Sent a DM in discord re this!

**Comment by themandalore** [comment]
Hey @DanTehrani , any update on this?  Still working on it or has it been deprecated in favor of another approach?

**Comment by DanTehrani** [comment]
@themandalore 
Yes it has been deprecated!

Further exploration will happen here: https://github.com/personaelabs/shockwave-plus
