### ISSUE TITLE
[Hoplite] Try integrating the EVM verifier

### ISSUE THREAD

**Issue by DanTehrani** [personaelabs/spartan-ecdsa#27]
## Motivation
Flesh out the unknown unknowns of the integration with the EVM verifier. We're planning to use [snark-verifier](https://github.com/privacy-scaling-explorations/snark-verifier/tree/main/snark-verifier) which is also [used by Axiom](https://github.com/axiom-crypto/snark-verifier).
There might be some type/lib compatibility issues, so we want to address those asap.

## Scope
- Add an executable (in `hoplite_circuit/src/bin`) that generates an EVM verifier for a given Halo2 circuit using [snark-verifier](https://github.com/privacy-scaling-explorations/snark-verifier/tree/main/snark-verifier).

## DoD
- Open a PR targetting the `hoplite` branch

**Comment by lsankar4033** [comment]
@DanTehrani lmk if i should take a look at this!
