### ISSUE TITLE
Publish circuits as a package

### ISSUE THREAD

**Issue by lsankar4033** [personaelabs/spartan-ecdsa#28]
Suggest publishing `packages/circuits` as an npm package similar to `circomlib`.

This would allow importing via `node_modules` similar to how we [often import circomlib](https://github.com/personaelabs/spartan-ecdsa/blob/main/packages/circuits/eff_ecdsa_membership/eff_ecdsa.circom#L4).

Little bit of an anti-pattern, but this would significantly help code re-use for libraries using spartan-ecdsa circuits (like nym)!

Happy to do this myself, but wanted to get your thoughts @DanTehrani

**Comment by DanTehrani** [comment]
Closing since already published! https://www.npmjs.com/package/@personaelabs/spartan-ecdsa-circuits
