### ISSUE TITLE
"yarn build" command reports an error

### ISSUE THREAD

**Issue by imamtom** [personaelabs/spartan-ecdsa#34]
There is no relevant error reported in the closed issue, so I have to ask for help, thank you very much!

imlee@imleeubuntu:~/work/spartan/spartan-ecdsa$ yarn && yarn build
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.64s.
yarn run v1.22.19
$ sh ./scripts/build.sh && lerna run build
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished release [optimized] target(s) in 0.13s
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 8.08s
[INFO]: 📦   Your wasm pkg is ready to publish at /home/imlee/work/spartan/spartan-ecdsa/packages/spartan_wasm/../spartan_wasm/build.
invalid prime number
previous errors were found
![20230429175547](https://user-images.githubusercontent.com/35050208/235296700-bccf47b1-e410-441b-b1a8-13367c03a138.png)

**Comment by DanTehrani** [comment]
Hi @imamtom.

I think you need to install Circom with secq256k1 support. I added instruction on how to do that in the README: https://github.com/personaelabs/spartan-ecdsa/tree/main#build

**Comment by DanTehrani** [comment]
Closing since inactive for a while!
