### ISSUE TITLE
Address membership circuit optimization

### ISSUE THREAD

**Issue by githubassets** [personaelabs/spartan-ecdsa#35]
Hello. We want to use this library for on-chain address membership verification. But the current implementation takes 6 seconds to verify the witness in browser. How could we optimize verification so it would work efficiently on-chain?

**Comment by DanTehrani** [comment]
@githubassets  We currently don't have a plan to support on-chain verification, as we don't think on-chain verification of spartan-ecdsa proofs is feasible. We're considering a different approach using a different proof system compatible with on-chain verification, and we hope to share more information about it soon!

**Comment by githubassets** [comment]
Understood. Thank you.

**Comment by MisiakGeo** [comment]
Hello all, since this post, one year has passed. Do you have any plans or know of an approach we can use for on-chain verification of these proofs?

**Comment by DanTehrani** [comment]
> Hello all, since this post, one year has passed. Do you have any plans or know of an approach we can use for on-chain verification of these proofs?

We're not working on this proof system anymore, and have no plans on implementing onchain verification.
I don't know any solutions for verifying spartan-ecdsa proofs either.
