### ISSUE TITLE
Curve for Powers of tau

### ISSUE THREAD

**Issue by biscuitdey** [personaelabs/spartan-ecdsa#39]
How can I use secq256k1 curve to generate the powers of tau (using the snarkjs library)? Any guidance would be helpful.

**Comment by Yiheng-Liu** [comment]
Hi, have you found the solution to the issue?

**Comment by biscuitdey** [comment]
@Yiheng-Liu Add your circuit to the `test_circuit` directory in the [spartan wasm generator](https://github.com/personaelabs/spartan-ecdsa/tree/main/packages/spartan_wasm) and `build_wasm.sh` script to generate your circuit wasm. You can then use the circuit wasm and `await snarkjs.wtns.calculate(input, wasmFile, witness);` to generate your witness.

**Comment by Yiheng-Liu** [comment]
Thx a lot for the reponse, I'll give a shot

**Comment by Yiheng-Liu** [comment]
> @Yiheng-Liu Add your circuit to the `test_circuit` directory in the [spartan wasm generator](https://github.com/personaelabs/spartan-ecdsa/tree/main/packages/spartan_wasm) and `build_wasm.sh` script to generate your circuit wasm. You can then use the circuit wasm and `await snarkjs.wtns.calculate(input, wasmFile, witness);` to generate your witness.

@biscuitdey It seems only output the witness. To generate the proof, you still need the power of tau(or zkey), how do you generate the proof then?

**Comment by biscuitdey** [comment]
@Yiheng-Liu 

````
const calculateCircuitWitness = async (input: any, wasmFile: string) => {
  const witness: {
    type: string;
    data?: any;
  } = {
    type: 'mem',
  };

  await snarkjs.wtns.calculate(input, wasmFile, witness);
  return witness;
};

````




````
 const witness = await calculateCircuitWitness(inputs, pathToCircuitWasm);
     const circuitBinary = await loadCircuit(pathToCircuit);

    //TODO: Add circuit public inputs ==> serialize(Object.values(inputs.public))
    const circuitPublicInputs: Uint8Array = new Uint8Array();

    const proof = spartan.default.prove(
      circuitBinary,
      witness.data,
      circuitPublicInputs,
    );
````


pathToCircuit is the `.circuit` file and pathToCircuitWasm is the `.wasm` file.

**Comment by Yiheng-Liu** [comment]
> @Yiheng-Liu
> 
> ```
> const calculateCircuitWitness = async (input: any, wasmFile: string) => {
>   const witness: {
>     type: string;
>     data?: any;
>   } = {
>     type: 'mem',
>   };
> 
>   await snarkjs.wtns.calculate(input, wasmFile, witness);
>   return witness;
> };
> ```
> 
> ```
>  const witness = await calculateCircuitWitness(inputs, pathToCircuitWasm);
>      const circuitBinary = await loadCircuit(pathToCircuit);
> 
>     //TODO: Add circuit public inputs ==> serialize(Object.values(inputs.public))
>     const circuitPublicInputs: Uint8Array = new Uint8Array();
> 
>     const proof = spartan.default.prove(
>       circuitBinary,
>       witness.data,
>       circuitPublicInputs,
>     );
> ```
> 
> pathToCircuit is the `.circuit` file and pathToCircuitWasm is the `.wasm` file.

Thanks a lot for the help, I'll give a shot.
