### ISSUE TITLE
Complete Addition Constraint

### ISSUE THREAD

**Issue by varunthakore** [personaelabs/spartan-ecdsa#42]
Great work ! Learning a lot going through the repo ! Just a small doubt....

https://github.com/personaelabs/spartan-ecdsa/blob/3827e5de67f6c0d32df92519df0c797b6de66d07/packages/circuits/eff_ecdsa_membership/secp256k1/add.circom#L83

Shouldn't  the above constraint be as follows ??
```
signal lambda <== ((lambdaB - lambdaA) * isXEqual.out) + lambdaA
```

**Comment by DanTehrani** [comment]
Glad to hear it!

`lambdaA`  is 0 when `isXEqual.out = 1` (line 75), so we don't need to subtract `lambdaA` when `isXEqual.out = 1`
https://github.com/personaelabs/spartan-ecdsa/blob/3827e5de67f6c0d32df92519df0c797b6de66d07/packages/circuits/eff_ecdsa_membership/secp256k1/add.circom#L75C48-L75C60

**Comment by varunthakore** [comment]
Got it ! Thanks a lot !
