### ISSUE TITLE
Membership proving

### ISSUE THREAD

**Issue by DanTehrani** [personaelabs/spartan-ecdsa#8]
Please feel free to work on only one of the sub-tasks!

Premise

The eff ecdsa proving/verification has been implemented. We also want to implement membership proving before launch. ~~After the Merkle hasher (either Poseidon or MiMC) is ready, we can fully implement membership proving, but I think some structural work/adjacent work can be done even without the Merkle hasher.~~ the Merkle hasher is ready!

Sub-tasks 
- [x] Implement membership prover in Typescript
- [x] Implement membership verifier in Typescript (pls add `membership_verifier.ts` [here](https://github.com/personaelabs/spartan-ecdsa/tree/main/packages/lib/src/core) and the tests [here](https://github.com/personaelabs/spartan-ecdsa/tree/main/packages/lib/tests))
- [x]  Get membership proving + proof verification working in [benchmark/web](https://github.com/personaelabs/spartan-ecdsa/tree/main/packages/benchmark/web)/ (i.e. in frontend) using the above impl

Dev related scripts
- [membership_circuit.sh](https://github.com/personaelabs/spartan-ecdsa/blob/main/scripts/membership_circuit.sh) will generate all the necessary circuit artifacts, and output them under `packages/circuits/build`
- other commands are written in the [readme](https://github.com/personaelabs/spartan-ecdsa/tree/main/packages/lib#readme)!

**Comment by DanTehrani** [comment]
@vb7401 
I updated the sub-tasks! Can we work on the membership verifier (the second one)?

**Comment by lsankar4033** [comment]
@vb7401 i think I understand what's necessary for this and can take it on as well! understand you've got a busy wkend so if don't hear anything once I finish some other tasks will jump on this

**Comment by lsankar4033** [comment]
workign on membership_verifier
