### ISSUE TITLE
Test prover with wallet signatures

### ISSUE THREAD

**Issue by DanTehrani** [personaelabs/spartan-ecdsa#9]
Either
- Use a wallet to sign messages instead of `ecsign` in benchmark/web/
- Create a new frontend example directory showcasing proving with various wallets

**Comment by lsankar4033** [comment]
@DanTehrani I can take this on while @vb7401 is off!

**Comment by DanTehrani** [comment]
@lsankar4033  That would be great! thanks!

**Comment by DanTehrani** [comment]
@lsankar4033 
Actually I need to push some changes first (including things related to only exposing address_membership and pubkey_membership), so I'll let you know when the lib becomes somewhat stable.

**Comment by lsankar4033** [comment]
ah ok! I was working on it, but will pause once I get the signature with rainbowkit/wagmi working. can then just swap in new API
